Dynamic memory options
ARMmbed/mbed-client pull request #423
Opened 2017-03-02 11:36 UTC by tpihlaja

Discussion on handling dynamic memory allocations in mbed-client - based on prototype implementation.

2017-03-02 11:38 UTC, tpihlaja commented
Automatic checks will fail because test applications should initialize dynamic memory somewhere before mbed client classes are used.

2017-03-03 16:11 UTC, TeroJaasko requested changes

2017-03-03 16:11 UTC, TeroJaasko commented on source/include/m2mdynamicmemory.h
> +    void operator delete[] (void * ptr);
This system needs also a way to keep the original, libc allocator in place, without touching eg. "operator new" at all.

2017-03-03 16:11 UTC, TeroJaasko commented on source/include/m2mdynamicmemory.h
> +    static void *memory_alloc(uint16_t size);
Doesn't this uint16_t cause now a bunch of warnings as the client uses uin32_t and/or size_t on many places?

2017-03-06 06:54 UTC, tpihlaja commented on mbed-client/m2mbase.h
> +class M2MBase : public M2MReportObserver, public M2MDynamicMemory {
The namespace overload of new/delete seems to be prohibited by C++ standard. Anyways we could first make namespace changes and then try the overload in different environments. I have a separate ticket for namespace update. Maybe separate namespaces for application and core part. To me inheritance seems more clear way to do "dynamic memory options". It is a bit more brute force and maybe some complications with multiple inheritance might rise, but so far it has worked fine.

2017-03-06 06:56 UTC, tpihlaja commented on source/m2mdynamicmemory.cpp
> +    printf("\nM2M memory failure: %u\n", fail);
These can be considered temporary debug prints. I should study the mbed_trace system a bit before changing to use it.

2017-03-06 06:59 UTC, tpihlaja commented on source/include/m2mdynamicmemory.h
> +    static void *memory_alloc(uint16_t size);
yes probably, however we should first make dynmemLIB itself more flexible and build up functionality from there. Now the library seems to work "at 16-bit".

2017-03-06 07:04 UTC, tpihlaja commented on source/include/m2mdynamicmemory.h
> +    void operator delete[] (void * ptr);
Yes, there are no flags in header file currently. I should recheck if module builds without any configuration flag. Just introducing functions shouldn't touch them...?

2017-03-06 07:05 UTC, tpihlaja commented on source/m2mnsdlinterface.cpp
> +                 &(memory_alloc), &(memory_free));
Allright. When introducing new wrappers I tried to get rid of as many old ones as possible.

2017-03-06 07:08 UTC, tpihlaja commented on source/m2mdynamicmemory.cpp
> +    memTotal+=size; memCount++;
Ok.

2017-03-14 07:22 UTC, tpihlaja commented on source/m2mnsdlinterface.cpp
> +                 &(memory_alloc), &(memory_free));
In fact signatures seemed to be same:
-void* __nsdl_c_memory_alloc(uint16_t size)

Both used uint16_t type size parameter.

2017-03-17 09:22 UTC, kjbracey-arm commented
I've assume this will be properly integrated with the existing ns_dynmemlib, and you're not really intending to add a second heap manager to the build?

2017-03-17 09:48 UTC, yogpan01 commented
Agreed with @kjbracey-arm , this extension should be integrated with existing dynmemlib so that other components can also utilize this feature.
@tpihlaja FYI. To begin with this new component can be part of nanostack-libservice , if directly integrating into existing dynmemlib is too big task at the moment.

2017-03-17 10:00 UTC, kjbracey-arm commented
I would assume the existing nsdynmemlib API would be easily mapped to to the updated implementation by just passing a fixed heap handle.

And then there should be some way to get that base handle for the case where your system does want mbed-client or other components to share the "main" dynmemlib heap, rather than create a separate one.

2017-03-31 08:23 UTC, kjbracey-arm commented
On the smallest platforms, it can be useful to restrict to 16 bits, even if the architecture in principle supports bigger. MSP430 is an example - it has 32-bit size_t, but we don't want/need to use that, and we know our heap(s) will be <64K.  Using size_t everywhere for all object sizes can be inefficient from a RAM point of view.

We probably want a typedef for the internal size type, to leave that possibility open. Note that presumably the internal heap implementation should use that too - as I recall it's using just "int", so this current API be giving 32-bit API but 16-bit heap on the MSP430.

There's also the potential possibility for heap objects being <64K but the heap total being >64K, which I don't think has been properly thought about.  You might want different types for heap size and individual object size.

In standard C, size_t is the appropriate size for an object, and there's no type to describe the size of a heap. In this sort of embedded heap, actually size_t is the appropriate size for the heap, but the size for the objects could be smaller.

2017-03-31 09:23 UTC, tpihlaja commented
Inner working of dynmemLIB definitely needs some work to support latest size_t API change. 64K maximum heap size sounds small to me. If that is the fact then we should keep the original implementation. With size_t we aimed for generic implementation. I guess we could still (with size_t in API) limit heap and object size somehow to keep inner working simpler and more memory efficient.

2017-03-31 09:39 UTC, kjbracey-arm commented
Using size_t is generic, but excessively fat for some of our embedded targets. Having your own specific typedef allows a build-time choice independent of the system.

We certainly want to go above 64K total for the heap - I'm not too concerned about making the heap total stats APIs 32-bit, and I thought that had already been done somewhat. So I'd be okay with those numbers just being size_t.

But for the individual heap objects, so far they've always been way less than 64K, so having a typedef for the object size which is used both in APIs and in the internal heap structure would maintain existing flexibility - we could define it as smaller than size_t on teeny platforms.

And that size type could be maybe exposed in higher application APIs too - there's a whole bunch of fixed uint16_ts in APIs that I'd like to see explanded, but I wouldn't want them to be forced to size_t on every platform.

2018-04-17 10:28 UTC, closed without merging