Add templates for issues/pull requests
ARMmbed/mbed-client pull request #450
Opened 2017-03-23 21:00 UTC by JanneKiiskila

2017-03-24 11:51 UTC, TeroJaasko approved these changes
Fine by me. I assue these templates are tried and tested on some other repos already?

2017-03-24 16:01 UTC, teetak01 requested changes

2017-03-24 16:01 UTC, teetak01 commented on .github/issue_template.md
> +reporting the the issue then directly to
Remove this part.

2017-03-27 20:57 UTC, JanneKiiskila commented
These were based on the templates from the raas-client. Preview shows what they look like.

2017-03-28 05:37 UTC, teetak01 approved these changes

2018-04-17 10:29 UTC, closed without merging